"""Emit the paper's parameter table from the registry (Markdown + CSV).

Generated rather than hand-maintained so the table cannot drift from the code.
Reviewers asked for this table explicitly; it goes in the paper regardless of
what the sensitivity sweep finds.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from asiot.parameters import PARAMETERS, default_value  # noqa: E402

GROUP_TITLES = {
    "interaction_probability": "Interaction probability (Eq. 25)",
    "expected_success": "Expected cooperation success (Eq. 27)",
    "trust_dynamics": "Trust and social-tie dynamics (Eqs. 28, 38, 48)",
    "preference": "Preference (Eq. 8)",
    "privacy": "Privacy risk and gate (Eqs. 20-21)",
    "social_weight": "Adaptive social weight (Eq. 47)",
    "utility_weights": "Multi-objective utility weights (Eq. 46)",
    "utility_terms": "Utility component coefficients (Eqs. 40-45)",
    "external_baseline": "External baseline assumptions",
}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--markdown", default="docs/parameter_table.md")
    ap.add_argument("--csv", default="docs/parameter_table.csv")
    ap.add_argument("--sweep-range", default="+/-25%, +/-50%")
    args = ap.parse_args()

    rows = []
    for parameter in PARAMETERS:
        rows.append({
            "symbol": parameter.symbol,
            "config_field": parameter.field,
            "meaning": parameter.meaning,
            "default": f"{default_value(parameter):g}",
            "swept_range": args.sweep_range,
            "equation": parameter.equation,
            "constraint": (f"sum-to-1 group: {parameter.simplex}" if parameter.simplex
                           else ("[0,1]" if parameter.unit_interval else "unbounded")),
            "note": parameter.note,
        })

    Path(args.csv).parent.mkdir(parents=True, exist_ok=True)
    with open(args.csv, "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)

    lines = [
        "# Parameter table",
        "",
        "Generated by `scripts/make_parameter_table.py` from",
        "`src/asiot/parameters.py`. Do not edit by hand: the registry is the",
        "single source of truth, and `tests/test_parameter_registry.py` fails if",
        "a model coefficient is added without an entry here.",
        "",
        f"Every parameter is swept one-at-a-time at {args.sweep_range} of its default",
        "by `scripts/run_sensitivity.py`. Weights belonging to a sum-to-one group are",
        "renormalised across the group when perturbed, since an unconstrained change",
        "would not be a valid configuration.",
        "",
        f"**{len(rows)} tunable coefficients.**",
        "",
    ]
    for group, title in GROUP_TITLES.items():
        members = [p for p in PARAMETERS if p.group == group]
        if not members:
            continue
        lines += [f"## {title}", "",
                  "| Symbol | Config field | Meaning | Default | Range | Equation | Constraint | Notes |",
                  "|---|---|---|---|---|---|---|---|"]
        for parameter in members:
            row = next(r for r in rows if r["config_field"] == parameter.field)
            lines.append(
                f"| `{row['symbol']}` | `{row['config_field']}` | {row['meaning']} | "
                f"{row['default']} | {row['swept_range']} | {row['equation']} | "
                f"{row['constraint']} | {row['note']} |"
            )
        lines.append("")

    Path(args.markdown).write_text("\n".join(lines))
    print(f"wrote {args.markdown} and {args.csv} ({len(rows)} parameters)")


if __name__ == "__main__":
    main()
